### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by ribafs** [Mortaro/curious-crud#1]
Que no README.md apareça um guia bem rápido de instalação e configuração, tipo:

npm install
Edição do Application.njs para configurar o banco

E a documentação seja para complementar.
npm start

Aqui, após estes procedimentos abrindo http://localhost:5000 no navegador a tela abre em branco.

**Comment by Mortaro** [comment]
Obrigado pela sugestão! Vou adicionar a sugestão dos passos de instalação em todos os projetos gerados pelo npx create-nullstack-app.

O projeto roda em http://localhost:5000/products a url raiz será ultilizada para um exemplo no próximo vídeo

**Comment by Mortaro** [comment]
@ribafs Implementada tua sugestão, Obrigado novamente. 💖

Agora esse repo tem os passos no README.md e todos os novos projetos criados com npx create-nullstack-app também!
